"""
Project: ProdaptNLService
Author: Abishek KJ
Date: 25-May-2021
"""

service: prodaptnl
frameworkVersion: '2'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-south-1

functions:
  ProdaptNLService:
    handler: handler.get_user_posts_comments
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /prodapt/service/posts
          method: get
          cors: true
      - http:
          path: /prodapt/service/post/{post_id}
          method: get
          cors: true
      - http:
          path: /prodapt/service/comment/{comment_id}
          method: get
          cors: true

custom:
  pythonRequirements:
    dockerizePip: non-linux
